test_average (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... FAIL
test_to_degrees (__main__.TestExercice) ... FAIL
test_to_farenheit (__main__.TestExercice) ... FAIL
test_to_radians (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_to_celsius (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 71, in test_to_celsius
    self.assertListEqual(
AssertionError: Lists differ: [32.0, -13.0, 843.8000000000001] != [-17.77777777777778, -31.666666666666664, 232.77777777777777]

First differing element 0:
32.0
-17.77777777777778

- [32.0, -13.0, 843.8000000000001]
+ [-17.77777777777778, -31.666666666666664, 232.77777777777777] : Mauvais calcul de farenheit -> celsius

======================================================================
FAIL: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 59, in test_to_degrees
    self.assertListEqual(
AssertionError: Lists differ: [(114.59155902616465, 6875.493541569879, 41[194 chars]241)] != [(79.0980174562859, 5.881047377154118, 29.6[197 chars]998)]

First differing element 0:
(114.59155902616465, 6875.493541569879, 412529.6124941927)
(79.0980174562859, 5.881047377154118, 29.612494192724625)

- [(114.59155902616465, 6875.493541569879, 412529.6124941927),
-  (-229.1831180523293, -13750.987083139758, -825059.2249883855),
-  (286.4788975654116, 17188.7338539247, 1031324.0312354818),
-  (234.3397382085067, 14060.384292510402, 843623.0575506241)]
+ [(79.0980174562859, 5.881047377154118, 29.612494192724625),
+  (-278.1960349125718, 48.23790524569176, 0.7750116145507491),
+  (257.74504364071475, -15.297381557114704, 44.031235481811564),
+  (213.95544569810457, -2.673258113725865, 23.057550624127998)] : Mauvais calcul de radians -> degres

======================================================================
FAIL: test_to_farenheit (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 83, in test_to_farenheit
    self.assertListEqual(
AssertionError: Lists differ: [-17.77777777777778, -31.666666666666668, 232.7777777777778] != [32.0, -13.0, 843.8000000000001]

First differing element 0:
-17.77777777777778
32.0

- [-17.77777777777778, -31.666666666666668, 232.7777777777778]
+ [32.0, -13.0, 843.8000000000001] : Mauvais calcul de celsius -> farenheit

======================================================================
FAIL: test_to_radians (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 40, in test_to_radians
    self.assertListEqual(
AssertionError: Lists differ: [18.76228945893904, 37.87393080834881, 15.707977812359399, 525.3441339391139] != [-0.08668468618238503, 0.17598251810595048, 6.283490739798685, 6.9973449482748]

First differing element 0:
18.76228945893904
-0.08668468618238503

- [18.76228945893904, 37.87393080834881, 15.707977812359399, 525.3441339391139]
+ [-0.08668468618238503, 0.17598251810595048, 6.283490739798685, 6.9973449482748] : Mauvais calcul de degres -> radians

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=4)
